### ISSUE TITLE
Validator does not see Beaconchain is synced to head

### ISSUE THREAD

**Issue by timmeh9432** [dappnode/DAppNodePackage-prysm-pyrmont#13]
I went through the basic setup, using an infura rpc for the beaconchain, however I can't see my validators as the validator node does not seem to find the beaconchain. Any ideas?

[logs-dappnode-package-DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth.txt](https://github.com/dappnode/DAppNodePackage-prysm-pyrmont/files/5596172/logs-dappnode-package-DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth.txt)
[logs-dappnode-package-DAppNodePackage-validator.prysm-pyrmont.dnp.dappnode.eth.txt](https://github.com/dappnode/DAppNodePackage-prysm-pyrmont/files/5596174/logs-dappnode-package-DAppNodePackage-validator.prysm-pyrmont.dnp.dappnode.eth.txt)

**Comment by dapplion** [comment]
You are using infura for the Eth1.x node, not the beacon chain. Your beacon node is syncing and the validator waiting for it to finish
```
time="2020-11-25 09:53:10" level=info msg="Waiting for beacon node to sync to latest chain head" prefix=validator
```
Be patient and it will start validating when it finishes syncing!

**Comment by timmeh9432** [comment]
You are right, my bad.

However I've been running the node for 2 days now and  it's been synced up to the head for a while (crosschecking with beaconchain's pyrmont explorer)

![image](https://user-images.githubusercontent.com/75018886/100239664-9252da00-2f29-11eb-9bcd-2f6f0fe5eebe.png)


EDIT : I've manually restarted the validator process and now it showed up as connected. However the logs right after the connection confirmation are hanging and are not up to the beaconchain timestamp, so the validator is not showing up.

[logs-dappnode-package-DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth (1).txt](https://github.com/dappnode/DAppNodePackage-prysm-pyrmont/files/5597343/logs-dappnode-package-DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth.1.txt)
[logs-dappnode-package-DAppNodePackage-validator.prysm-pyrmont.dnp.dappnode.eth (1).txt](https://github.com/dappnode/DAppNodePackage-prysm-pyrmont/files/5597347/logs-dappnode-package-DAppNodePackage-validator.prysm-pyrmont.dnp.dappnode.eth.1.txt)
