### ISSUE TITLE
12000 UDP

### ISSUE THREAD

**Issue by tbenr** [dappnode/DAppNodePackage-prysm-pyrmont#7]
https://github.com/dappnode/DAppNodePackage-prysm-pyrmont/blob/c5ad0b67e6a167ff61a2d07abb4cd43bb0f0775f/docker-compose.yml#L13

shouldn't be `12000/udp`?

**Comment by dapplion** [comment]
Thanks! Fixed 
https://github.com/dappnode/DAppNodePackage-prysm-pyrmont/blob/4876deb4d54388982fbdee9bbfa5a4963c869cb7/docker-compose.yml#L13
